// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD_wehqrOApTS7lSUgDntg1pN-SmHGLBg',
    appId: '1:579562761429:web:16f195c0a8bd7a9442465c',
    messagingSenderId: '579562761429',
    projectId: 'mobiledevelopment-21a42',
    authDomain: 'mobiledevelopment-21a42.firebaseapp.com',
    storageBucket: 'mobiledevelopment-21a42.firebasestorage.app',
    measurementId: 'G-ZELE1QJ9BL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP007J_c2Tv2DpZr-PnbioXWZXrLicN54',
    appId: '1:579562761429:android:686bdba7a0505efc42465c',
    messagingSenderId: '579562761429',
    projectId: 'mobiledevelopment-21a42',
    storageBucket: 'mobiledevelopment-21a42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-TLDE3q8EC1zKvb8LFvcukDaQJgVgIFA',
    appId: '1:579562761429:ios:b3c513aa02c126bb42465c',
    messagingSenderId: '579562761429',
    projectId: 'mobiledevelopment-21a42',
    storageBucket: 'mobiledevelopment-21a42.firebasestorage.app',
    iosBundleId: 'com.example.mobileDevelopment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-TLDE3q8EC1zKvb8LFvcukDaQJgVgIFA',
    appId: '1:579562761429:ios:b3c513aa02c126bb42465c',
    messagingSenderId: '579562761429',
    projectId: 'mobiledevelopment-21a42',
    storageBucket: 'mobiledevelopment-21a42.firebasestorage.app',
    iosBundleId: 'com.example.mobileDevelopment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD_wehqrOApTS7lSUgDntg1pN-SmHGLBg',
    appId: '1:579562761429:web:b3a724396f176f9d42465c',
    messagingSenderId: '579562761429',
    projectId: 'mobiledevelopment-21a42',
    authDomain: 'mobiledevelopment-21a42.firebaseapp.com',
    storageBucket: 'mobiledevelopment-21a42.firebasestorage.app',
    measurementId: 'G-HP52T5W4CP',
  );
}
